In [1]:
# import torch
# from torch.utils.data import Dataset
# from torch.utils.data import DataLoader
# import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series, DataFrame

Fish_Data= pd.read_csv('Fish.csv', sep='\t')
Fish_Data


Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [2]:
Fish_Species=Fish_Data['Species']
Fish_Species_list=[]
for i in range(0,159):
    Fish_Species_list.append(Fish_Species.iloc[i])

Fish_Species_list[i]
for i in range(0, 159):                 
    if Fish_Species_list[i] == "Bream":
        Fish_Species_list[i]  = 0        
    elif Fish_Species_list[i] == 'Roach':
        Fish_Species_list[i] = 1
    elif Fish_Species_list[i] == 'Whitefish':
        Fish_Species_list[i] =2
    elif Fish_Species_list[i]== 'Parkki':
        Fish_Species_list[i] =3
    elif Fish_Species_list[i] == 'Perch':
        Fish_Species_list[i]= 4
    elif Fish_Species_list[i]== 'Pike':
        Fish_Species_list[i]= 5
    else : 
        Fish_Species_list[i]= 6
Fish_Species_list=np.array(Fish_Species_list)
Fish_Species_list





array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6])

In [3]:
Fish_feature = DataFrame(Fish_Data, columns=['Weight', 'Length1','Length2','Length3','Height','Width'])
Fish_feature
#Fish_feature.shape = (159,6)

Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [5]:
Fish_feature_list=[]
for i in range(0,159):
    Fish_feature_list.append(Fish_feature.iloc[i].to_list())

# print(Fish_feature_list)   
Fish_feature_list=np.array(Fish_feature_list)
print(Fish_feature_list)


[[2.42000e+02 2.32000e+01 2.54000e+01 3.00000e+01 1.15200e+01 4.02000e+00]
 [2.90000e+02 2.40000e+01 2.63000e+01 3.12000e+01 1.24800e+01 4.30560e+00]
 [3.40000e+02 2.39000e+01 2.65000e+01 3.11000e+01 1.23778e+01 4.69610e+00]
 [3.63000e+02 2.63000e+01 2.90000e+01 3.35000e+01 1.27300e+01 4.45550e+00]
 [4.30000e+02 2.65000e+01 2.90000e+01 3.40000e+01 1.24440e+01 5.13400e+00]
 [4.50000e+02 2.68000e+01 2.97000e+01 3.47000e+01 1.36024e+01 4.92740e+00]
 [5.00000e+02 2.68000e+01 2.97000e+01 3.45000e+01 1.41795e+01 5.27850e+00]
 [3.90000e+02 2.76000e+01 3.00000e+01 3.50000e+01 1.26700e+01 4.69000e+00]
 [4.50000e+02 2.76000e+01 3.00000e+01 3.51000e+01 1.40049e+01 4.84380e+00]
 [5.00000e+02 2.85000e+01 3.07000e+01 3.62000e+01 1.42266e+01 4.95940e+00]
 [4.75000e+02 2.84000e+01 3.10000e+01 3.62000e+01 1.42628e+01 5.10420e+00]
 [5.00000e+02 2.87000e+01 3.10000e+01 3.62000e+01 1.43714e+01 4.81460e+00]
 [5.00000e+02 2.91000e+01 3.15000e+01 3.64000e+01 1.37592e+01 4.36800e+00]
 [3.40000e+02 2.95000e+01